### PR TITLE
Update readme typo :pencil2:

### PR DESCRIPTION
**Pull request by boon-cpu**

### CODE REVIEW

**Comment by wyatt** [comment]
LGTM!

**Review by wyatt — APPROVED** [review]

**Comment by ctrl-cheeb-del** [comment]
LGTM 👍

**Review by ctrl-cheeb-del — APPROVED** [review]

**Comment by driaug** [comment]
Great you caught this typo!

**Comment by boon-cpu** [comment]
LGTM

**Comment by alii** [comment]
LGTM like and describe

**Pull request merged**
